theme = "blackburn"
baseURL = "/"
languageCode = "en-us"
title = "Blog PRUEBA Github"
author = "Pedro J. Pérez"
copyright = "&copy; 2017"
canonifyurls = true
relativeurls = true
paginate = 7
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"


[indexes]
  tag = "tags"
  topic = "topics"


[permalinks]
    post = "/blog/:year/:month/:day/:slug/"

[params]
  # Shown in the home page
  subtitle = "pjperez's blog para aprender y relajarse (con R)"
  brand = "Peter<br>Pan"
  #brand = "R&F" creo que es poner una afoto
  # CSS name for highlight.js
  highlightjs = "github"   #androidstudio
  dateFormat = "02 Jan 2006"
  #custom_css = ["css/custom.css"]
  

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topics"    
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"  
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 6
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "pjpv4444"
  #facebook = "*"
  #instagram = "*"
  github = "perezp44"
  #stackoverflow = "*"
  #linkedin = "*"
