---
title: Tuneando el blog
author: Pedro J. Pérez
date: '2017-11-27'
topics:
  - blog
tags:
  - blog
slug: tuneando-el-blog
---

Este post lo utilizaré para ir apuntando lo que aprendo/soluciono al ir tuneando el blog.


Estoy tuneando el blog usando dos que he visto:

  - <https://www.mattcraddock.com/>
  - <http://yoshiharuyamashita.com/> del creador del theme
  - <https://simplystatistics.org/> de Rafa Irizarry, Roger Peng, and Jeff Leek 
  

Esta vez creo que medio entenderé como se hacen las web con html, css etc…

Tengo ya "muchos" post en el cabolo: el de vacas, uno sobre gestionar los kipplings de mi Kindle, otro de temperaturas en Valencia, cesáreas y más. Massa


## COSAS a recordar:**

- El logo (el ababol) está en el config-toml en `brand`. La afoto está en `./static/img/logo.jpg`, y el trozo de código está en `. /layout/partials/brand.html`. Me explico, eh!

- Cuando haces el deploy en Netlify  en las opciones de Build & Deploy has de (lo explica en blogdown):   
      - Build command: lo he dejado en blanco, creo que podía poner `hugo deploy`
      - Publish directory: public (esta es la carpeta del repo de Github q tiene en realidad el blog)
      - Production branch: master (lo tengo en la master branch del repo)

- Yihiu recomienda añadir al archivo `.gitignore` : 

```yaml
public  
blogdown
Thumbs.db  #- para windows users
```

- A yolo le he visto:


```yaml
https://www.shamindras.com/2017/12/31/getting-tuftesque-with-blogging/  
# Blogdown common gitignore files
# Source: https://github.com/rbind/yihui/blob/master/.gitignore
.Rproj.user
.Rhistory
.RData
.Ruserdata
public
static/figures
blogdown

# Source: https://github.com/kbroman/blog/blob/source/.gitignore
_cache/
drafts/
```

## COSAS a mejorar:

- Las imágenes las he de poner en `/static/` pero a mi me gustaría cargarlas directamente de Github, ¿Cómo?


- Lo mismo con los datos, me gustaría cargarlo desde Github (ahora los datos desde un pkg en Github)

- Las tablas que hago con kable me salen más feas en el blog que si las kniteo en RStudio



## ¿Probar?

- [[Figuring out images and disqus with blogdown]](http://kgilds.rbind.io/2017/12/13/images/). 



Bye